language: node_js
node_js:
- '0.12'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: github.com/jupyter/jupyter-js-terminal.git
  - secure: AIsE0tWS99Hn/AYSxCxh9Ki0pZcSGyw/ALy/2ZDzdYclRFZz9JG6CqiOvqOFVDZ6RXU2gHZDp/jI2Hi7beb/h3EqpfDtd80DMVOz6uC7eGuMy1GU7LjQ9pm3UX7p2MgLxKgV6fjOpYD7rbmcZ1JeK/jNSmRitZPGW6SesoPNT0EBSQPXYM/4M/ZWzoJhuo2slZsm+wtAl4U7M0N0FoWatQECTksyca661LwvOzoD5MqopzC5oO8yIC310JVMKwbmZqbHGYXyLbeLkS7OTPs9JtiqLrBey3cXlP8PL6hyFmDRT0lLoUy7kJglPkkwFvQ8MXnEkMsrtn7BDfbm6aVR/gG+fxG23+r14HnwjYGlPaUJRMYqa9ZlLFiqJo7QmZAVgHMLvdPiN7qn2yvDe9mGHCRoY3B3VofkCpABNhMBZvn1xVZ/ARggHkb5MyYzRvStf3cik67ZCcgY0UNwdQWS1j6JFuwMNPpgL1ZvtezYWiCxtnIvzOzZ22ZCrY37iG4LzTQSJMoxN/DNIHjo3wSfd3Y6O0wGhB6HlzMLnJiEMtDbwhZrA0ceU5O9pLPQZtPnU9RGraJZGPE76KEGCH3E+UC30jRBz2xKkD+vFofMQvb7xea9oO/+P58O5zgmsV3wt9NaZLS6GKtGEzm7nE1PUCx/ceiXxm19xbssngDD4D4=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
